In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('Social_Network_Ads.csv')
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [3]:
gen={'Male':1,'Female':0}
df.Gender=[gen[item]for item in df.Gender]
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510       1   19            19000          0
1  15810944       1   35            20000          0
2  15668575       0   26            43000          0
3  15603246       0   27            57000          0
4  15804002       1   19            76000          0

In [4]:
X=df[['Age','EstimatedSalary']]
Y=df['Purchased']
print(X,"\n",Y)

     Age  EstimatedSalary
0     19            19000
1     35            20000
2     26            43000
3     27            57000
4     19            76000
..   ...              ...
395   46            41000
396   51            23000
397   50            20000
398   36            33000
399   49            36000

[400 rows x 2 columns] 
 0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64


In [5]:
X.insert(0,'B0',1)
xt=X.T
print("X",X,"\nXT",xt)

X      B0  Age  EstimatedSalary
0     1   19            19000
1     1   35            20000
2     1   26            43000
3     1   27            57000
4     1   19            76000
..   ..  ...              ...
395   1   46            41000
396   1   51            23000
397   1   50            20000
398   1   36            33000
399   1   49            36000

[400 rows x 3 columns] 
XT                    0      1      2      3      4      5      6       7    \
B0                   1      1      1      1      1      1      1       1   
Age                 19     35     26     27     19     27     27      32   
EstimatedSalary  19000  20000  43000  57000  76000  58000  84000  150000   

                   8      9    ...    390    391    392    393    394    395  \
B0                   1      1  ...      1      1      1      1      1      1   
Age                 25     35  ...     48     47     45     60     39     46   
EstimatedSalary  33000  65000  ...  33000  23000  45000  42000  5

In [6]:
XTX=np.dot(xt,X)
print("XTX",XTX)


XTX [[          400         15062      27897000]
 [        15062        611006    1072601000]
 [     27897000    1072601000 2409485000000]]


In [7]:
XTXI=np.linalg.inv(XTX)
print("XTXI",XTXI)
XTY=np.dot(xt,Y)
print("XTY",XTY)
BHAT=np.dot(XTXI,XTY)
print("BHAT",BHAT)

XTXI [[ 4.05225685e-02 -8.02211160e-04 -1.12059465e-07]
 [-8.02211160e-04  2.33700867e-05 -1.11538095e-09]
 [-1.12059465e-07 -1.11538095e-09  2.20897064e-12]]
XTY [     143     6634 12337000]
BHAT [-9.09619165e-01  2.65605047e-02  3.82813004e-06]


In [10]:
age = 36
salary = 76000
y_pred=BHAT[0]+BHAT[1]*age+BHAT[2]*salary
print("Y_PRED",y_pred)
prediction=1/(1+(2.718)**-y_pred)

Y_PRED 0.3374968884064251


In [11]:
print("Value of sigmoid function : ",prediction)
if prediction>0.5:
    print("PREDICTION : YES")
else:
    print("PREDICTION : NO")

Value of sigmoid function :  0.5835738555144255
PREDICTION : YES
