In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('Social_Network_Ads.csv')
df.head(2)

User ID Gender  Age  EstimatedSalary  Purchased
0  15624510   Male   19            19000          0
1  15810944   Male   35            20000          0

In [3]:
gen={'Male':1,'Female':0}
df.Gender=[gen[item]for item in df.Gender]
df.head(2)

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510       1   19            19000          0
1  15810944       1   35            20000          0

In [4]:
X=df[['Age','EstimatedSalary']]
n = len(X)
n = int(0.70*n)

In [5]:
df = pd.read_csv('Social_Network_Ads.csv',nrows=n)

In [6]:
X=df[['Age','EstimatedSalary']]
Y=df['Purchased']
print(X,"\n",Y)

     Age  EstimatedSalary
0     19            19000
1     35            20000
2     26            43000
3     27            57000
4     19            76000
..   ...              ...
275   57            74000
276   38            71000
277   49            88000
278   52            38000
279   50            36000

[280 rows x 2 columns] 
 0      0
1      0
2      0
3      0
4      0
      ..
275    1
276    0
277    1
278    1
279    1
Name: Purchased, Length: 280, dtype: int64


In [7]:
X.insert(0,'B0',1)
xt=X.T
print("X",X,"\nXT",xt)

X      B0  Age  EstimatedSalary
0     1   19            19000
1     1   35            20000
2     1   26            43000
3     1   27            57000
4     1   19            76000
..   ..  ...              ...
275   1   57            74000
276   1   38            71000
277   1   49            88000
278   1   52            38000
279   1   50            36000

[280 rows x 3 columns] 
XT                    0      1      2      3      4      5      6       7    \
B0                   1      1      1      1      1      1      1       1   
Age                 19     35     26     27     19     27     27      32   
EstimatedSalary  19000  20000  43000  57000  76000  58000  84000  150000   

                   8      9    ...     270    271    272     273    274  \
B0                   1      1  ...       1      1      1       1      1   
Age                 25     35  ...      43     59     60      39     57   
EstimatedSalary  33000  65000  ...  133000  76000  42000  106000  26000   

    

In [8]:
XTX=np.dot(xt,X)
print("XTX",XTX)

XTX [[          280          9682      19176000]
 [         9682        363446     684980000]
 [     19176000     684980000 1648324000000]]


In [9]:
XTXI=np.linalg.inv(XTX)
print("XTXI",XTXI)
XTY=np.dot(xt,Y)
print("XTY",XTY)
BHAT=np.dot(XTXI,XTY)
print("BHAT",BHAT)

XTXI [[ 5.08534771e-02 -1.10568124e-03 -1.32132239e-07]
 [-1.10568124e-03  3.67314758e-05 -2.40109518e-09]
 [-1.32132239e-07 -2.40109518e-09  3.14165782e-12]]
XTY [     69    3071 6731000]
BHAT [-7.76039270e-01  2.03485849e-02  4.65561102e-06]


In [12]:
age = 36
salary = 76000
y_pred=BHAT[0]+BHAT[1]*age+BHAT[2]*salary
print("Y_PRED",y_pred)
prediction=1/(1+(2.718)**-y_pred)

Y_PRED 0.3103362227411173


In [13]:
print("Value of sigmoid function : ",prediction)
if prediction>0.5:
    print("PREDICTION : YES")
else:
    print("PREDICTION : NO")

Value of sigmoid function :  0.576959473516792
PREDICTION : YES
