In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('E:/GitHub Desktop/AI & ML/Assignment 6/MyData.csv')
df.head()

Y  X1  X2  X3
0  43  30  63  33
1  63  45  47  52
2  71  68  67  62
3  61  46  83  42
4  81  66  84  42

In [3]:
X = df.drop('Y', axis = 1)

In [4]:
X.insert(0,'B0',[1,1,1,1,1,1])

In [5]:
X = X.values
Y = df['Y'].values

In [6]:
Xt = X.T

In [7]:
Xt 

array([[ 1,  1,  1,  1,  1,  1],
       [30, 45, 68, 46, 66, 36],
       [63, 47, 67, 83, 84, 50],
       [33, 52, 62, 42, 42, 66]], dtype=int64)

In [8]:
XtX = Xt.dot(X)

In [9]:
print(XtX)

[[    6   291   394   297]
 [  291 15317 19723 14626]
 [  394 19723 27112 18991]
 [  297 14626 18991 15521]]


In [10]:
XtXInv = np.linalg.inv(XtX)

In [11]:
print(XtXInv)

[[ 1.69580230e+01  8.31914459e-02 -1.73130574e-01 -1.91055228e-01]
 [ 8.31914459e-02  1.89410821e-03 -1.54994977e-03 -1.48031635e-03]
 [-1.73130574e-01 -1.54994977e-03  2.35593088e-03  1.89084867e-03]
 [-1.91055228e-01 -1.48031635e-03  1.89084867e-03  2.80171396e-03]]


In [12]:
Xty = Xt.dot(Y)

In [13]:
print(Xty)

[  362 18653 24444 17899]


In [14]:
B = XtXInv.dot(Xty)

In [15]:
print(B)

[38.8730967   1.06294938 -0.15180574 -0.40655013]


In [16]:
X1 = 50
X2 = 70
X3 = 80
y = B[0] + B[1] * X1 + B[2] * X2 + B[3] * X3

In [17]:
print(y)

48.87015369722906


In [18]:
X1 = 30
X2 = 40
X3 = 50
y = B[0] + B[1] * X1 + B[2] * X2 + B[3] * X3

In [19]:
print(y)

44.36184213169186
