In [30]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [35]:
df=pd.read_csv('hiring.csv')
print(df)

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000


In [36]:
map={'one':1,'two':2,'three':3,'four':4,'five':5,'six':6,'seven':7,'eight':8,'nine':9,'ten':10,'eleven':11}
target_feature='experience'
df[target_feature]=df[target_feature].map(map)

In [37]:
print(df)

   experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         NaN                    8.0                           9      50000
1         NaN                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    NaN                           7      72000
7        11.0                    7.0                           8      80000


In [38]:

df['experience']=df['experience'].fillna(0)
print(df)

   experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         0.0                    8.0                           9      50000
1         0.0                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    NaN                           7      72000
7        11.0                    7.0                           8      80000


In [39]:
import math
med=math.floor(df['test_score(out of 10)'].mean())
print(med)
df['test_score(out of 10)'].fillna(med, inplace=True)
print(df['test_score(out of 10)'])

7
0     8.0
1     8.0
2     6.0
3    10.0
4     9.0
5     7.0
6     7.0
7     7.0
Name: test_score(out of 10), dtype: float64


In [40]:
lr=linear_model.LinearRegression()
x_train=df.drop('salary($)',axis=1)
print('x_train\n', x_train)
y_train=df['salary($)']
print('y_train\n',y_train)
lr.fit(x_train,y_train)

x_train
    experience  test_score(out of 10)  interview_score(out of 10)
0         0.0                    8.0                           9
1         0.0                    8.0                           6
2         5.0                    6.0                           7
3         2.0                   10.0                          10
4         7.0                    9.0                           6
5         3.0                    7.0                          10
6        10.0                    7.0                           7
7        11.0                    7.0                           8
y_train
 0    50000
1    45000
2    60000
3    65000
4    70000
5    62000
6    72000
7    80000
Name: salary($), dtype: int64


LinearRegression()

In [41]:
print(lr.coef_)

[2922.26901502 2221.30909959 2147.48256637]


In [42]:
print(lr.intercept_)

14992.65144669314


In [43]:
lr.predict([[2, 9, 6]])

array([53713.86677124])

In [44]:
lr.predict([[12, 10, 10]])

array([93747.79628651])