In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('E:/GitHub Desktop/AI & ML/Assignment 6/HPriceData.csv')
df.head()

Area  Bedrooms  Age   Price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [3]:
import math
med=math.floor(df['Bedrooms'].median())
print(med)
df['Bedrooms'].fillna(med, inplace=True)
df.head()

3


Area  Bedrooms  Age   Price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [4]:
X = df.drop('Price',axis = 1)
Y = df['Price']
print("X\n",X,"\nY\n",Y)

X
    Area  Bedrooms  Age
0  2600       3.0   20
1  3000       4.0   15
2  3200       3.0   18
3  3600       3.0   30
4  4000       5.0    8 
Y
 0    550000
1    565000
2    610000
3    595000
4    760000
Name: Price, dtype: int64


In [5]:
X.insert(0,'B0',[1,1,1,1,1])

In [6]:
X

B0  Area  Bedrooms  Age
0   1  2600       3.0   20
1   1  3000       4.0   15
2   1  3200       3.0   18
3   1  3600       3.0   30
4   1  4000       5.0    8

In [7]:
Xt = X.T

In [25]:
Xt

0       1       2       3       4
B0           1.0     1.0     1.0     1.0     1.0
Area      2600.0  3000.0  3200.0  3600.0  4000.0
Bedrooms     3.0     4.0     3.0     3.0     5.0
Age         20.0    15.0    18.0    30.0     8.0

In [26]:
XtX = Xt.dot(X)

In [27]:
print(XtX)

               B0        Area  Bedrooms       Age
B0            5.0     16400.0      18.0      91.0
Area      16400.0  54960000.0   60200.0  294600.0
Bedrooms     18.0     60200.0      68.0     304.0
Age          91.0    294600.0     304.0    1913.0


In [22]:
XtXInv = np.linalg.inv(XtX)

In [12]:
print(XtXInv)

[[ 2.90831875e+01  1.14437500e-03 -6.00493750e+00 -6.05437500e-01]
 [ 1.14437500e-03  2.06875000e-06 -1.61187500e-03 -1.16875000e-04]
 [-6.00493750e+00 -1.61187500e-03  2.22568750e+00  1.80187500e-01]
 [-6.05437500e-01 -1.16875000e-04  1.80187500e-01  1.86875000e-02]]


In [13]:
Xty = Xt.dot(Y)

In [14]:
print(Xty)

B0          3.080000e+06
Area        1.025900e+10
Bedrooms    1.132500e+07
Age         5.438500e+07
dtype: float64


In [15]:
BHAT = XtXInv.dot(Xty)

In [28]:
print(BHAT)

[ 3.83725e+05  1.37250e+02 -2.60250e+04 -6.82500e+03]


In [17]:
X1 = 3000
X2 = 3
X3 = 40
y = BHAT[0] + BHAT[1] * X1 + BHAT[2] * X2 + BHAT[3] * X3

In [18]:
print(y)

444400.0000000023


In [19]:
X1 = 2500
X2 = 4
X3 = 5
y = BHAT[0] + BHAT[1] * X1 + BHAT[2] * X2 + BHAT[3] * X3

In [20]:
print(y)

588625.000000005
